### ISSUE TITLE
Support for binary job bodies

### ISSUE THREAD

**Issue by mzapletal** [xetorthio/jedisque#4]
Jedisque currently supports String-based job bodies only. The body, however, gets serialized to/from a byte representation when being sent/consumed to/from Jedis. When dealing with byte representations in an application anyway, this results in unnecessary serialization overhead. Hence, it would be nice if Jedisque provides support for byte[] bodies as well.

**Comment by xetorthio** [comment]
This is definitely something we'll be adding and soon. I will leave this issue open until this has been addressed.

**Comment by marcosnils** [comment]
I've released Jedisque 0.0.4 which contains this feature. Should be in artifactory soon.
